export interface Email {
  id: string
  sender: string
  subject: string
  preview: string
  body: string
  date: string
  read: boolean
  starred: boolean
  important: boolean
  priority: "high" | "medium" | "low"
  spam: boolean
  trash: boolean
  attachments?: string[]
  folders?: string[] // IDs of folders this email belongs to
}

export const emails: Email[] = [
  {
    id: "1",
    sender: "GitHub",
    subject: "Action required: Your repository has security vulnerabilities",
    preview:
      "We found potential security vulnerabilities in your repository. Please review and update your dependencies as soon as possible.",
    body: "Hello,\n\nWe've detected several critical security vulnerabilities in your repository. These vulnerabilities could potentially expose sensitive data or allow unauthorized access to your systems.\n\nPlease review the security alerts in your repository dashboard and update the affected dependencies as soon as possible.\n\nThank you for helping keep GitHub secure!",
    date: "2023-03-15T10:30:00Z",
    read: false,
    starred: true,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "security-alerts", "urgent-action"],
  },
  {
    id: "2",
    sender: "AWS Billing",
    subject: "Your AWS bill is 40% higher than last month",
    preview: "Your AWS bill for February 2023 is $1,240.50, which is 40% higher than your January bill of $885.35.",
    body: "Dear Customer,\n\nYour AWS bill for February 2023 is $1,240.50, which is 40% higher than your January bill of $885.35.\n\nWe've detected unusual activity in the following services:\n- EC2: $450.20 (up from $320.15)\n- S3: $220.30 (up from $150.20)\n- Lambda: $180.00 (up from $95.00)\n\nWe recommend reviewing your resource usage and implementing cost optimization strategies.\n\nBest regards,\nAWS Billing Team",
    date: "2023-03-14T09:15:00Z",
    read: false,
    starred: false,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "billing", "urgent-action"],
  },
  {
    id: "3",
    sender: "Stripe Payments",
    subject: "Payment failed for subscription",
    preview:
      "The payment for your Pro Plan subscription ($49.99/month) has failed. Please update your payment method to avoid service interruption.",
    body: "Hello,\n\nWe're writing to let you know that your recent payment for the Pro Plan subscription ($49.99/month) has failed.\n\nThis could be due to insufficient funds, an expired card, or a temporary issue with your payment provider.\n\nPlease update your payment method in your account settings as soon as possible to avoid any interruption to your service.\n\nIf you need any assistance, please don't hesitate to contact our support team.\n\nBest regards,\nStripe Payments Team",
    date: "2023-03-13T16:45:00Z",
    read: true,
    starred: true,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "billing", "urgent-action"],
  },
  {
    id: "4",
    sender: "LinkedIn",
    subject: "You have 5 new connection requests",
    preview:
      "You have 5 new connection requests waiting for your response. Connect with professionals in your industry.",
    body: "Hi there,\n\nYou have 5 new connection requests waiting for your response on LinkedIn.\n\nConnecting with professionals in your industry can help you expand your network and discover new opportunities.\n\nClick the button below to view and respond to your connection requests.\n\nBest regards,\nThe LinkedIn Team",
    date: "2023-03-12T11:20:00Z",
    read: true,
    starred: false,
    important: false,
    priority: "medium",
    spam: false,
    trash: false,
    folders: ["social"],
  },
  {
    id: "5",
    sender: "Dropbox",
    subject: "Your storage is almost full",
    preview:
      "You've used 95% of your Dropbox storage. Upgrade now to ensure you don't lose the ability to sync new files.",
    body: "Hello,\n\nYour Dropbox storage is almost full! You've used 95% of your available storage space.\n\nTo ensure you can continue to sync and store new files, consider upgrading to a plan with more storage or freeing up space by removing unnecessary files.\n\nUpgrade today and get 2TB of storage, plus additional features like Dropbox Passwords and Vault.\n\nBest regards,\nThe Dropbox Team",
    date: "2023-03-11T14:30:00Z",
    read: false,
    starred: false,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "follow-up"],
  },
  {
    id: "6",
    sender: "Twitter",
    subject: "Security alert: New login to your account",
    preview: "We detected a new login to your Twitter account from a new device in San Francisco, CA. Was this you?",
    body: "Hi there,\n\nWe noticed a new login to your Twitter account from a device or location we don't recognize.\n\nNew login details:\n- Date: March 10, 2023\n- Time: 9:45 PM UTC\n- Location: San Francisco, CA, USA\n- Device: iPhone 13 Pro, iOS 16.3.1\n\nIf this was you, you can ignore this message. If you don't recognize this activity, please secure your account immediately by changing your password and enabling two-factor authentication.\n\nStay safe,\nTwitter Security Team",
    date: "2023-03-10T21:50:00Z",
    read: true,
    starred: true,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "security-alerts", "urgent-action"],
  },
  {
    id: "7",
    sender: "Netflix",
    subject: "New TV shows and movies added this week",
    preview:
      "Check out the latest additions to Netflix this week, including new seasons of your favorite shows and exclusive movies.",
    body: "Hello,\n\nWe've added lots of new TV shows and movies to Netflix this week!\n\nNew this week:\n- The Last of Us: Season 1\n- John Wick: Chapter 4\n- Stranger Things: Season 5\n- The Queen's Gambit: Limited Series\n\nWe've also added new documentaries, anime, and kids' content. Log in now to start watching!\n\nEnjoy,\nYour Netflix Team",
    date: "2023-03-09T08:15:00Z",
    read: true,
    starred: false,
    important: false,
    priority: "low",
    spam: false,
    trash: false,
    folders: ["newsletters"],
  },
  {
    id: "8",
    sender: "Slack",
    subject: "Daily digest: 15 unread messages in 3 channels",
    preview: "You have 15 unread messages in 3 channels, including mentions in #team-updates and #general.",
    body: "Hi there,\n\nHere's your daily digest from Slack:\n\nYou have 15 unread messages in 3 channels:\n- #team-updates: 7 messages (2 mentions)\n- #general: 5 messages (1 mention)\n- #random: 3 messages\n\nYou also have 2 direct messages waiting for your response.\n\nClick below to catch up on the conversation.\n\nThe Slack Team",
    date: "2023-03-08T17:30:00Z",
    read: false,
    starred: false,
    important: true,
    priority: "medium",
    spam: false,
    trash: false,
    folders: ["follow-up"],
  },
  {
    id: "9",
    sender: "Zoom",
    subject: "Reminder: Team Meeting in 30 minutes",
    preview: "Your scheduled meeting 'Weekly Team Sync' starts in 30 minutes. Click to join or add to your calendar.",
    body: "Hi there,\n\nThis is a reminder that your scheduled Zoom meeting 'Weekly Team Sync' starts in 30 minutes.\n\nMeeting details:\n- Date: March 8, 2023\n- Time: 10:00 AM - 11:00 AM (Your local time)\n- Meeting ID: 123 456 7890\n- Passcode: 654321\n\nYou can join the meeting by clicking the button below or using the Meeting ID and Passcode.\n\nBest regards,\nZoom Team",
    date: "2023-03-08T09:30:00Z",
    read: true,
    starred: false,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "follow-up"],
  },
  {
    id: "10",
    sender: "Apple",
    subject: "Receipt for your recent purchase",
    preview: "Thank you for your purchase. Your receipt for App Store & iTunes Store is attached.",
    body: "Dear Customer,\n\nThank you for your purchase from the App Store & iTunes Store.\n\nOrder ID: MXLKJH987654\nDate: March 7, 2023\nTotal: $9.99\n\nItem:\n- Spotify Premium (Monthly Subscription) - $9.99\n\nPayment Method:\n- Visa ending in 1234\n\nIf you didn't make this purchase, please contact Apple Support immediately.\n\nRegards,\nApple",
    date: "2023-03-07T13:45:00Z",
    read: true,
    starred: false,
    important: false,
    priority: "low",
    spam: false,
    trash: false,
    folders: ["billing"],
  },
  {
    id: "11",
    sender: "Amazon",
    subject: "Your package has been delivered",
    preview: "Your package with order #114-2875623-7895623 has been delivered. It was handed to a resident.",
    body: "Hello,\n\nYour package has been delivered!\n\nOrder #114-2875623-7895623\nDelivered: March 6, 2023 at 2:30 PM\nDelivery method: Handed to resident\n\nPackage contents:\n- Wireless Earbuds\n- Phone Case\n- USB-C Cable (2-pack)\n\nIf you have any issues with your delivery, please contact us within 30 days.\n\nThank you for shopping with Amazon!\n\nThe Amazon Delivery Team",
    date: "2023-03-06T14:35:00Z",
    read: true,
    starred: false,
    important: false,
    priority: "medium",
    spam: false,
    trash: false,
    folders: ["inbox"],
  },
  {
    id: "12",
    sender: "Discount Supplements",
    subject: "LAST CHANCE: 80% OFF ALL SUPPLEMENTS TODAY ONLY!!!",
    preview: "DON'T MISS OUT!!! MASSIVE CLEARANCE SALE ON ALL PRODUCTS! BUY NOW BEFORE IT'S TOO LATE!",
    body: "🔥🔥🔥 MASSIVE SALE ALERT!!! 🔥🔥🔥\n\nDON'T MISS OUT ON OUR BIGGEST SALE EVER!!!\n\n80% OFF ALL SUPPLEMENTS TODAY ONLY!!!\n\nProtein Powders, Pre-Workouts, Vitamins, Weight Loss, and MORE!!!\n\nFREE SHIPPING on orders over $20!!!\n\nUSE CODE: MASSIVE80 at checkout!!!\n\nHURRY - SALE ENDS MIDNIGHT TONIGHT!!!\n\n🔥🔥🔥 CLICK NOW TO SHOP!!! 🔥🔥🔥",
    date: "2023-03-05T11:20:00Z",
    read: false,
    starred: false,
    important: false,
    priority: "low",
    spam: true,
    trash: false,
    folders: ["spam", "promotions"],
  },
  {
    id: "13",
    sender: "PayPal",
    subject: "Action required: Confirm your identity",
    preview:
      "We've noticed some unusual activity on your account. Please confirm your identity to continue using PayPal services.",
    body: "Dear Customer,\n\nWe've noticed some unusual activity on your PayPal account and have temporarily limited some features.\n\nTo restore full access to your account, please confirm your identity by clicking the link below and following the instructions.\n\nThis is a standard security measure we take to protect our users and ensure the safety of their accounts.\n\nIf you did not attempt to access your account recently, please contact our support team immediately.\n\nThank you for your cooperation,\nPayPal Security Team",
    date: "2023-03-04T16:10:00Z",
    read: false,
    starred: false,
    important: true,
    priority: "high",
    spam: true,
    trash: false,
    folders: ["spam", "security-alerts"],
  },
  {
    id: "14",
    sender: "Jira",
    subject: "Task assigned to you: Implement new authentication flow",
    preview: "John Smith has assigned you a high-priority task: Implement new authentication flow (PROJ-235).",
    body: "Hello,\n\nJohn Smith has assigned you a task in the Project X workspace.\n\nTask: Implement new authentication flow\nID: PROJ-235\nPriority: High\nDue date: March 15, 2023\n\nDescription:\nImplement the new OAuth 2.0 authentication flow as discussed in the planning meeting. This should include social login options and improved security measures.\n\nYou can view the full task details and add comments by clicking the button below.\n\nRegards,\nJira Notifications",
    date: "2023-03-03T10:25:00Z",
    read: true,
    starred: true,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    folders: ["priority", "urgent-action"],
  },
  {
    id: "15",
    sender: "DocuSign",
    subject: "Documents ready for signature: Contract renewal",
    preview: "You have documents waiting for your signature: Contract renewal (expires in 7 days).",
    body: "Hello,\n\nYou have documents waiting for your signature.\n\nDocument: Contract renewal\nSent by: Sarah Johnson (sarah.johnson@company.com)\nExpires: March 10, 2023\n\nPlease review and sign these documents at your earliest convenience. The signing process only takes a few minutes and can be completed on any device.\n\nClick the button below to review and sign the documents.\n\nThank you,\nDocuSign",
    date: "2023-03-02T14:50:00Z",
    read: false,
    starred: true,
    important: true,
    priority: "high",
    spam: false,
    trash: false,
    attachments: ["Contract_Renewal_2023.pdf", "Terms_and_Conditions.pdf"],
    folders: ["priority", "urgent-action"],
  },
]

